import { Inter } from "next/font/google";
import "./globals.css";
import { UserRoleProvider } from "@/components/UserContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "NCT Scheduling",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className={`${inter.className} antialiased`}>
        <UserRoleProvider>
          {children}
        </UserRoleProvider>
      </body>
    </html>
  );
}
